WHENEVER SQLERROR EXIT SQL.SQLCODE;

BEGIN
  EXECUTE IMMEDIATE 'DROP USER hr CASCADE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -1918 THEN
      RAISE;
    END IF;
END;
/

CREATE USER hr IDENTIFIED BY HrUser_2026;
ALTER USER hr ACCOUNT UNLOCK;

GRANT CONNECT, RESOURCE TO hr;
GRANT CREATE VIEW TO hr;
GRANT CREATE SEQUENCE TO hr;
GRANT CREATE PROCEDURE TO hr;
GRANT CREATE TRIGGER TO hr;
GRANT UNLIMITED TABLESPACE TO hr;
